export enum AttackEffect {
    BLUNT_LIGHT,
    BLUNT_HEAVY,
    SLASH_DIAGONAL,
    SMASH,
    SLASH_HEAVY,
    SLASH_HORIZONTAL,
    SLASH_VERTICAL,
    NONE,
    FIRE,
    POISON,
    SHIELD,
    LIGHTNING
}